# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Publish new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 1.0.5)"
        required: true
        type: string

jobs:
  release:
    name: Create and Publish Release
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Interface Analyser
        run: swift build -c release --disable-sandbox

      - name: Get Binary Path
        id: binary
        run: echo "BINARY_PATH=$(swift build -c release --show-bin-path)/interface-analyser" >> $GITHUB_ENV

      - name: Create Release Draft
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          draft: true
          generate_release_notes: true
          files: ${{ env.BINARY_PATH }}

      - name: Publish Release
        run: gh release edit v${{ inputs.version }} --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
